# Logistic regression example from lecture

In [41]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Wlv/7CS033/weight-height.csv')

In [ ]:
df

In [43]:
X=df.drop('Gender',axis=1)
y=df['Gender']

In [46]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [45]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [50]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X=sc.fit_transform(X)

In [51]:
from sklearn import linear_model
clf = linear_model.LogisticRegression()
fitted_model = clf.fit(X, y)

In [52]:
clf.coef_

array([[-1.76889234, 23.66840149]])

In [53]:
clf.intercept_

array([-10.26391683])

In [54]:
prediction_result = clf.predict([(70,180)])

In [55]:
prediction_result

array([1])

In [56]:
(-1.76889234*70)+(23.66840149*180)+(-10.26391683)

4126.22588757

# Logistic regression binary classification

In [12]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=4, n_redundant=4, n_classes=2, random_state=1)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)


# define the multinomial logistic regression model
model = LogisticRegression()
# fit the model on the whole dataset
model.fit(X_train, y_train)

# predict the class label
y_pred = model.predict(X_test)

In [ ]:
y_pred

In [64]:
y_test

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,

In [ ]:
y_pred

# Logistic regression multi-class classification

## OvR

In [65]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

model = LogisticRegression(multi_class="ovr")

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)


## OvO

In [66]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsOneClassifier

# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

model = LogisticRegression()

# Define the OvO strategy
ovo = OneVsOneClassifier(model)

# Train the model
ovo.fit(X_train, y_train)

# Make predictions
y_pred = ovo.predict(X_test)


## Multinomial

In [67]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsOneClassifier

# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

model = LogisticRegression(multi_class="multinomial")

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Neural network binary classification

In [69]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=1000, n_features=10, n_informative=4, n_redundant=4, n_classes=2, random_state=1)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)


In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, BatchNormalization, Dropout
from keras import layers
from keras.regularizers import l2,l1
from sklearn.model_selection import StratifiedKFold as kfold

In [71]:
model=Sequential()
model.add(Dense(10, input_shape=(10,), activation='relu'))
model.add(Dense(7,activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [72]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=50)

In [ ]:
# plot loss during training
from matplotlib import pyplot
pyplot.subplot(211)
pyplot.title('Loss')
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()
# plot accuracy during training
pyplot.subplot(212)
pyplot.title('Accuracy')
pyplot.plot(history.history['accuracy'], label='train')
pyplot.plot(history.history['val_accuracy'], label='test')
pyplot.legend()
pyplot.show()

# Neural network multi class classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, BatchNormalization, Dropout
from keras import layers
from keras.regularizers import l2,l1
from sklearn.model_selection import StratifiedKFold as kfold
from keras.utils import to_categorical

In [2]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
y = to_categorical(y)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [82]:
y[0]

array([0., 1., 0.], dtype=float32)

In [9]:
# WARNING: Your model works if you use the sigmoid function, but you must use the softmax function
model=Sequential()
model.add(Dense(10, input_shape=(10,), activation='relu'))
model.add(Dense(7,activation='relu'))
model.add(Dense(3, activation='softmax'))

In [10]:
# WARNING: The model works with binary crossentropy, but you must use categorical_crossentropy
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=50)

# Evaluation metrics

In [ ]:
# Creating the confusion matrics for predictions
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
y_pred=model.predict(X_test)
cm1 = confusion_matrix(y_test, y_pred, labels=[0,1])
disp = ConfusionMatrixDisplay(confusion_matrix=cm1,display_labels=['class 1','class 2'])
disp.plot()
plt.title("CM")

In [ ]:
y_test

In [15]:
def confusion_metrics (conf_matrix):

    TP = conf_matrix[1][1]
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    print('True Positives:', TP)
    print('True Negatives:', TN)
    print('False Positives:', FP)
    print('False Negatives:', FN)

    # calculate accuracy
    conf_accuracy = (float (TP+TN) / float(TP + TN + FP + FN))

    # calculate mis-classification
    conf_misclassification = 1- conf_accuracy

    # calculate the sensitivity
    conf_sensitivity = (TP / float(TP + FN))
    # calculate the specificity
    conf_specificity = (TN / float(TN + FP))

    # calculate precision
    conf_precision = (TN / float(TN + FP))
    # calculate f_1 score
    conf_f1 = 2 * ((conf_precision * conf_sensitivity) / (conf_precision + conf_sensitivity))
    print('-'*50)
    print(f'Accuracy: {round(conf_accuracy,2)}')
    print(f'Mis-Classification: {round(conf_misclassification,2)}')
    print(f'Sensitivity: {round(conf_sensitivity,2)}')
    print(f'Specificity: {round(conf_specificity,2)}')
    print(f'Precision: {round(conf_precision,2)}')
    print(f'f_1 Score: {round(conf_f1,2)}')

In [ ]:
print('model metrics\n')
confusion_metrics(cm1)