# Tasks

## Task 6.1: Download the 'Tweets' dataset from Canvas. Classify the sentiments in the dataset using six classifiers and calculate all evaluation metrics (10%).
### NOTE: If the running time is too long, you can reduce the number of samples.
### NOTE: You should comment on your code and explain what each part is doing
### NOTE: You should improve the model's performance as much as possible

In [8]:
############# WRITE THE CODE IN THIS CELL ####################
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/cbikash/MREs-workshops/refs/heads/main/Tweets.csv"
data = pd.read_csv(url)

data.describe()
data.isna().sum()

sentiment    0
tweet        0
dtype: int64

In [9]:
data

sentiment                                              tweet
0              0  Eating a gyro for breakfast at the airport. Pr...
1              1  Well .. .you fall of the 'horse' and get strai...
2              0  thanks for the responses but when is it really...
3              0                        depressed.! fuuck my life! 
4              1  is LMAO, just thinkin of the 80/20 rule.....wo...
...          ...                                                ...
39995          1     @TafiApple Awww... you retweeted me!  Thanks! 
39996          1  Getting some coffee before I faceplant. Guess ...
39997          0                @bernderk it could *not* be worse! 
39998          1  I thought about getting a bunny...but my beagl...
39999          0  So I have my new phone. Now I just have no con...

[40000 rows x 2 columns]

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
# Load dataset
df = pd.read_csv("https://raw.githubusercontent.com/cbikash/MREs-workshops/refs/heads/main/Tweets.csv")  # Replace with your actual file path

# Preprocess text and labels
X = df['tweet'].astype(str)
y = df['sentiment']

# Vectorize text using TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
X_vectorized = vectorizer.fit_transform(X)

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y_encoded, test_size=0.2, random_state=42)

# Define classifiers
classifiers = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": MultinomialNB(),
    "SVM": SVC(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting": GradientBoostingClassifier()
}

# Evaluate each classifier
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    print(f"\nClassifier: {name}")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
    print(f"Precision: {precision_score(y_test, y_pred):.2f}")
    print(f"Recall: {recall_score(y_test, y_pred):.2f}")
    print(f"F1 Score: {f1_score(y_test, y_pred):.2f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


Classifier: Logistic Regression
Accuracy: 0.75
Precision: 0.74
Recall: 0.78
F1 Score: 0.76
Confusion Matrix:
[[2908 1115]
 [ 862 3115]]

Classifier: Naive Bayes
Accuracy: 0.74
Precision: 0.76
Recall: 0.69
F1 Score: 0.72
Confusion Matrix:
[[3172  851]
 [1235 2742]]

Classifier: SVM
Accuracy: 0.76
Precision: 0.73
Recall: 0.80
F1 Score: 0.76
Confusion Matrix:
[[2865 1158]
 [ 798 3179]]

Classifier: Random Forest
Accuracy: 0.73
Precision: 0.72
Recall: 0.75
F1 Score: 0.74
Confusion Matrix:
[[2888 1135]
 [ 989 2988]]

Classifier: KNN
Accuracy: 0.52
Precision: 0.54
Recall: 0.21
F1 Score: 0.30
Confusion Matrix:
[[3321  702]
 [3139  838]]

Classifier: Gradient Boosting
Accuracy: 0.66
Precision: 0.61
Recall: 0.88
F1 Score: 0.72
Confusion Matrix:
[[1752 2271]
 [ 486 3491]]


############ WRITE YOUR REPORT IN THIS CELL (IF APPLICABLE) #############




